USE [master]
GO
IF EXISTS(SELECT NULL FROM sys.databases WHERE name = 'HD')
BEGIN
	DECLARE @SQL varchar(max)
	SELECT @SQL = COALESCE(@SQL, '') + 'Kill ' + Convert(varchar, SPId) + ';'
	FROM MASTER ..SysProcesses
	WHERE DBId = DB_Id(N'_HD') AND SPId <> @@SPId
	EXEC(@SQL)

DROP DATABASE [HD]
END
GO


USE [master]
GO

CREATE DATABASE [HD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HD', FILENAME = N'D:\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HD.mdf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'HD_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HD_log.ldf' , SIZE = 26816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HD] SET ARITHABORT OFF 
GO

ALTER DATABASE [HD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HD] SET  MULTI_USER 
GO

ALTER DATABASE [HD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HD] SET  READ_WRITE 
GO


